name: Merge upstream branches
on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        fetch-depth: 0
        ref: 'test222'
      - name: Merge upstream
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'netbox@users.noreply.github.com'
          # git reset --hard HEAD~4
          git remote add upstream https://github.com/cinemagoer/cinemagoer.git
          git pull upstream/master
          gut push origin test222 
          
