name: Merge upstream branches
on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Merge upstream
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'netbox@users.noreply.github.com'
          git remote add upstream https://github.com/cinemagoer/cinemagoer.git
          git fetch upstream
          git checkout -b temp-branch upstream/master
          git checkout main
          git merge temp-branch main
          git push origin main

          


